##  Print Reports
#load(".RData")

print(' ', quote=FALSE)
print(' ', quote=FALSE)
print('         CPU 30-day Report', quote=FALSE)
print(CPU_30d_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print('         Core-Count 30-day Report', quote=FALSE)
print(COR_30d_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print('         Memory 30-day Report', quote=FALSE)
print(MEM_30d_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Run Queue 30-day Report", quote=FALSE)
print(RUN_30d_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Alive Process 30-day Report", quote=FALSE)
print(PRC_30d_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Active Process 30-day Report", quote=FALSE)
print(ACT_30d_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Physical I/O 30-day Report (KB/s)",  quote=FALSE)
print(PIO_30d_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Network Input Packets 30-day Report", quote=FALSE)
print(NTI_30d_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Network Output Packets 30-day Report", quote=FALSE)
print(NTO_30d_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Interrupts 30-day Report", quote=FALSE)
print(INT_30d_Report)


