##  Print All-day Reports
#load(".RData")

print(' ', quote=FALSE)
print(' ', quote=FALSE)
print('         CPU All-day Report', quote=FALSE)
print(CPU_All_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print('         Core-Count All-day Report', quote=FALSE)
print(COR_All_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print('         Memory All-day Report', quote=FALSE)
print(MEM_All_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Run Queue All-day Report", quote=FALSE)
print(RUN_All_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Alive Process All-day Report", quote=FALSE)
print(PRC_All_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Active Process All-day Report", quote=FALSE)
print(ACT_All_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Physical I/O All-day Report (KB/s)",  quote=FALSE)
print(PIO_All_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Network Input Packets All-day Report", quote=FALSE)
print(NTI_All_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Network Output Packets All-day Report", quote=FALSE)
print(NTO_All_Report)
print(' ', quote=FALSE)
print(' ', quote=FALSE)
print("         Interrupts All-day Report", quote=FALSE)
print(INT_All_Report)

